#general site settings
title: Sarayu Services For Children
description: Service With Smile
email: suryakavutarapu@gmail.com


#menu settings

menu:
- {name: Home, url: '#home'}
- {name: Vission, url: '#vission'}
- {name: Services, url: '#services'}
- {name: Inspirations, url: '#inspirations'}



#seo content  
seo:
  description: ' we care for such children by giving our helping hand for their livelyhood and encouraging them in each any every aspect to achieve their dreams in real life'
  rel-author: 'http://suryakavutarapu.wordpress.com'
  rel-publisher: 'http://www.github.com/SuryaKavutarapu'



#vission
vissionp1: "Vast number of children who are living on the streets,exploited for labor,victims of trafficking,or participating in armed groups. the number of orphans nearby and fail to account for many children who are among the most vulnerable and most in need of a family. Many of the children living in orphanages or on the streets are known as 'orphans.'Although one or even both of their parents may be alive, orphans rarely see their parents or experience life in a family. Some never do. Global orphan statistics shed virtually no light on the reality of the vast number of orphans who have one or two living parents, yet experience life as if they did not.We offer support and opportunities that enable these children to remain safely intact and provide resources to help them thrive."

vissionp2: >
    "The hearts of small children are delicate organs.A cruel beginning in this world can twist them into curious shapes.The heart of a hurt child can shrink so that forever afterward it is hard and pitted as the seed of a peach.Or again,the heart of such a child may fester and swell until it is misery to carry within the body, easily chafed and hurt by the most ordinary things.
     -- Carson Smith "

vissionp3: > 
   "It is not the physical pain that endangers orphans the most. It is the mental pain caused by stress from years and years of being neglected,pushed aside, disregarded, unloved, and made to feel undeserving, and in almost all cases, made to feel like a possession rather than an equal human being. Even more it is the lack of unconditional love, the right to be accepted, as a child and to be loved, as a child, no matter what you do is the most wounding"


#services

service:   > 
  "We care for the children who lost their life away from their parents and just born babies who left because of their family situations. we care for such children by giving our helping hand for their livelyhood and encouraging them in each any every aspect to achieve their dreams in real life.Every children is not poor by birth,their conditions and environment among them makes poor.we give helping hand for them and guide them to know what is going to be in future and making them to meet their challenges in their own life. We may not not help hundrends of children but a helping hand in a right situation gives a lot for their lively hood.we don't need any of our financial support we just need the same helping hand from your side by giving the linformation or location of such a children if u find any where around ur premises."



#---quotes--


quotes: 
 - {data: "If you can't feed a hundred people,then feed just one.", author: "Mother Teresa" }
 - {data: "No man is so poor as to have nothing worth giving. Give what you have. To someone it may be better than you dare to think", author: "Henry Wadsworth Longfellow" }
 - {data: "Love heals people-- both the ones who give it and the ones who receive it." , author: "Karl Menninger" }
 - {data: "Children will not remember you for the material things you provided, but for the feeling that you cherished them", author: "Richard Evans" }
 - {data: "Love is a wonderful thing. You never have to take it away from one person to give it to another. There's always more than enough to go around." , author: "Pamela deRoy" }